### ISSUE TITLE
Edit Profile - Add Profile Picture Feature

### ISSUE THREAD

**Issue by amnevins** [RecursiveThinking/recursive_thinking_website#16]
Build the Add Profile Picture Feature.  
Considerations/Guidelines:
- Should be a file picker
- Optimally an html5 standard that supports mobile

**Comment by sethborne** [comment]
FYI - the changes made had an issue when the page was resized (wider) at a certain point, it broke off the image.

I fixed this today by removing the wrapping label tags, and changing them to div tags.  now the span follows the image no matter the resize

**Comment by clayton-perszyk** [comment]
Hmmm... seems to have broken the file upload functionality. I'll look at it later, but i think the label needs to be in there somehow, or it wont work. Otherwise we have to keep the default file type displayed by the browser.
<img width="183" alt="screen shot 2018-02-22 at 12 29 30 pm" src="https://user-images.githubusercontent.com/7948430/36562553-331a612e-17cc-11e8-9b0b-85fc6b06f358.png">

**Comment by sethborne** [comment]
actually - i think i just got a solution

I just wrapped your label in the div...it doesn't float, and the dialog still come up.  Pushing it now.

**Comment by clayton-perszyk** [comment]
NIce! That's what I was thinking of doing.
