### ISSUE TITLE
cleanup/Isolate CSS

### ISSUE THREAD

**Issue by amnevins** [RecursiveThinking/recursive_thinking_website#46]
Prefix all CSS selctors not in main.css with the id of the template they belong too so that conflicts dont happen with main.
Only media queries in Main
Prefer REM

**Comment by sethborne** [comment]
I always liked It's the End of the World, never got the popularity of Losing my Religion...

**Comment by amnevins** [comment]
Lol - End of the world is the perfect song to describe the state our css is becoming

**Comment by sethborne** [comment]
So...one thing to chat about tomorrow.  I think we should put all responsive CSS ( media queries ) - into its own file at the end of all the CSS links?

**Comment by amnevins** [comment]
I agree ^

**Comment by sethborne** [comment]
cool.

**Comment by sethborne** [comment]
Question - if the header.css and footer.css are prefixed with tag selectors (header and footer, respectively) will this work? 

Or do both of these files need a id for the header/or footer instead of the tag?  

Since these shouldn't (well, I'll make sure they don't) get split out to any other css files, unless something would get added to responsive.css... It seems like the tag selectors should be enough?

**Comment by MynockSpit** [comment]
Probably? The only issue is that header and footer could exist in other parts of the UI -- semantically they simply mean they're the header and footer of a section. Might be safer to do something like `body>header`.

**Comment by sethborne** [comment]
cool, I can give a rabbit a carrot...   >

**Comment by sethborne** [comment]
so everything is prefixed, and all responsive in responsive.css
